### ISSUE TITLE
Help: what does these failure messages mean?

### ISSUE THREAD

**Issue by zhouchengming99** [colcon/colcon-output#27]
Hello,
I pull the latest ros2 stack code and run colcon build/test, many these error messages show up when colcon test-result --verbose:

build/action_msgs/test_results/action_msgs/xmllint.xunit.xml: 1 test, 0 errors, 1 failure, 0 skipped
- action_msgs.xmllint package.xml
  <<< failure message
    Diff with 329 lines
  >>>
build/action_tutorials_cpp/test_results/action_tutorials_cpp/xmllint.xunit.xml: 1 test, 0 errors, 1 failure, 0 skipped
- action_tutorials_cpp.xmllint package.xml
  <<< failure message
    Diff with 329 lines
  >>>
build/action_tutorials_interfaces/test_results/action_tutorials_interfaces/xmllint.xunit.xml: 1 test, 0 errors, 1 failure, 0 skipped
- action_tutorials_interfaces.xmllint package.xml
  <<< failure message
    Diff with 329 lines
  >>>

**Comment by zhouchengming99** [comment]
From the stdout log:
test 37
      Start 37: xmllint

37: Test command: /usr/bin/python3 "-u" "/home/administrator/nvme/ros2_stack/install/share/ament_cmake_test/cmake/run_test.py" "/home/administrator/nvme/ros2_stack/build/action_msgs/test_results/action_msgs/xmllint.xunit.xml" "--package-name" "action_msgs" "--output-file" "/home/administrator/nvme/ros2_stack/build/action_msgs/ament_xmllint/xmllint.txt" "--command" "/home/administrator/nvme/ros2_stack/install/bin/ament_xmllint" "--xunit-file" "/home/administrator/nvme/ros2_stack/build/action_msgs/test_results/action_msgs/xmllint.xunit.xml"
37: Test timeout computed to be: 60
37: -- run_test.py: invoking following command in '/home/administrator/nvme/ros2_stack/src/ros2/rcl_interfaces/action_msgs':
37:  - /home/administrator/nvme/ros2_stack/install/bin/ament_xmllint --xunit-file /home/administrator/nvme/ros2_stack/build/action_msgs/test_results/action_msgs/xmllint.xunit.xml
37: File 'package.xml' is invalid:
37: error : No such file or directory
37: warning: failed to load external entity "http://download.ros.org/schema/package_format3.xsd"
37: Schemas parser error : Failed to locate the main schema resource at 'http://download.ros.org/schema/package_format3.xsd'.
37: WXS schema http://download.ros.org/schema/package_format3.xsd failed to compile
37:
37: 1 files are invalid
37: -- run_test.py: return code 1
37: -- run_test.py: verify result file '/home/administrator/nvme/ros2_stack/build/action_msgs/test_results/action_msgs/xmllint.xunit.xml'
37/37 Test #37: xmllint ...........................................***Failed    0.89 sec

97% tests passed, 1 tests failed out of 37

**Comment by zhouchengming99** [comment]
I saw this line: "37: File 'package.xml' is invalid:"
Is it saying the package.xml of the package action_msgs? That file is there no problem.
so I don't know what the meaning of this message...

**Comment by zhouchengming99** [comment]
@dirk-thomas Could you give me some help and instructions? 👍

**Comment by dirk-thomas** [comment]
The error message is coming from one of the tests - specifically from `ament_xmllint` which checks that XML files are well formed and if applicable validate against a schema.

The main problem seems to be:

> Schemas parser error : Failed to locate the main schema resource at 'http://download.ros.org/schema/package_format3.xsd'.

Since the URL is accessible for me it might be a network connection problem on your side.

Since this is not a problem in the code of this repository I will go ahead and close this ticket. Please feel free to continue commenting.
